### ISSUE TITLE
Missing OpenSSL

### ISSUE THREAD

**Issue by stephenc01** [linuxserver-archive/docker-nntp2nntp#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

The init fails as OpenSSL is required to general keys

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by CHBMB** [comment]
Just a quick test and can confirm this, seems to be the update from Alpine 3.10 to 3.11 that broke it.  Will submit a PR
